/*
 * Redaktioneller Startbestand für PatchDex.
 * `sourceUrl` verweist auf Projektseiten, Entwickler-Repositories oder
 * ursprüngliche Community-Threads – nie auf ROM-Spiegel.
 * Letzte redaktionelle Linkprüfung: 12.09.2026
 */
window.PATCHDEX_GAMES = [
  {
    id: 1,
    slug: "pokemon-unbound",
    name: "Pokémon Unbound",
    type: "ROM-Hack",
    engine: "GBA",
    status: "Komplett",
    language: "Englisch",
    base: "FireRed",
    version: "2.1.1.1",
    sourceKind: "Community-Thread",
    sourceUrl: "https://www.pokecommunity.com/threads/pok%C3%A9mon-unbound-completed.382178/",
    featured: 100,
    color: "#405fbb",
    symbol: "U",
    tags: ["Neue Region", "Story", "QoL"],
    description: "Eine große neue Region, eigene Story, Missionen und zahlreiche moderne Komfortfunktionen."
  },
  {
    id: 2,
    slug: "pokemon-radical-red",
    name: "Pokémon Radical Red",
    type: "ROM-Hack",
    engine: "GBA",
    status: "Komplett",
    language: "Englisch",
    base: "FireRed",
    version: "4.1",
    sourceKind: "Community-Thread",
    sourceUrl: "https://www.pokecommunity.com/threads/pok%C3%A9mon-radical-red-version-4-1-released-gen-9-dlc-pokemon-character-customization-now-available.437688/",
    featured: 99,
    color: "#e14c45",
    symbol: "R",
    tags: ["Schwierig", "Gen 9", "QoL"],
    description: "FireRed als anspruchsvoller Kampf-Hack mit modernen Mechaniken, Teamvorschau und vielen Spielmodi."
  },
  {
    id: 3,
    slug: "pokemon-gaia",
    name: "Pokémon Gaia",
    type: "ROM-Hack",
    engine: "GBA",
    status: "Komplett",
    language: "Englisch",
    base: "FireRed",
    version: "3.2",
    sourceKind: "Community-Thread",
    sourceUrl: "https://www.pokecommunity.com/threads/pok%C3%A9mon-gaia.326118/",
    featured: 91,
    color: "#5a9156",
    symbol: "G",
    tags: ["Neue Region", "Klassisch", "Story"],
    description: "Eine klassische Reise durch die Orbtus-Region mit Ruinen, Mega-Entwicklung und eigener Handlung."
  },
  {
    id: 4,
    slug: "firered-rocket-edition",
    name: "Pokémon FireRed: Rocket Edition",
    type: "ROM-Hack",
    engine: "GBA",
    status: "Komplett",
    language: "Englisch",
    base: "FireRed",
    version: "1.0",
    sourceKind: "Projektseite",
    sourceUrl: "https://rocket-edition.com/",
    featured: 94,
    color: "#343b38",
    symbol: "R",
    tags: ["Team Rocket", "Story", "Kanto"],
    description: "Erzählt die bekannte Kanto-Reise aus Sicht eines Team-Rocket-Rekruten – inklusive Diebstahlmechanik."
  },
  {
    id: 5,
    slug: "pokemon-emerald-rogue",
    name: "Pokémon Emerald Rogue",
    type: "ROM-Hack",
    engine: "GBA",
    status: "In Entwicklung",
    language: "Englisch",
    base: "Emerald",
    version: "2.2.0",
    sourceKind: "Entwickler-Repository",
    sourceUrl: "https://github.com/Pokabbie/pokeemerald-rogue",
    featured: 97,
    color: "#258b70",
    symbol: "◆",
    tags: ["Roguelike", "Hoenn", "Replay"],
    description: "Ein tiefes Roguelike mit zufälligen Routen, Runs, Meta-Fortschritt und enormem Wiederspielwert."
  },
  {
    id: 6,
    slug: "pokemon-rowe",
    name: "Pokémon R.O.W.E.",
    type: "ROM-Hack",
    engine: "GBA",
    status: "In Entwicklung",
    language: "Englisch",
    base: "Emerald",
    version: "2.x",
    sourceKind: "Community-Thread",
    sourceUrl: "https://www.pokecommunity.com/threads/pokemon-r-o-w-e-an-open-world-version-of-pok%C3%A9mon-emerald-gen-8-following-pok%C3%A9mon-costumes-and-much-more.442592/",
    featured: 90,
    color: "#44a27e",
    symbol: "R",
    tags: ["Open World", "Hoenn", "Randomizer"],
    description: "Hoenn als offene Welt mit skalierenden Gegnern, frei wählbarer Route und vielen optionalen Modi."
  },
  {
    id: 7,
    slug: "pokemon-inclement-emerald",
    name: "Pokémon Inclement Emerald",
    type: "ROM-Hack",
    engine: "GBA",
    status: "Komplett",
    language: "Englisch",
    base: "Emerald",
    version: "1.13",
    sourceKind: "Community-Thread",
    sourceUrl: "https://www.pokecommunity.com/threads/pok%C3%A9mon-inclement-emerald-a-decomp-difficulty-hack.457039/",
    featured: 86,
    color: "#2d8f75",
    symbol: "I",
    tags: ["Schwierig", "Hoenn", "Gen 7"],
    description: "Ein umfangreicher Difficulty-Hack mit neu ausbalancierten Pokémon und mehreren Schwierigkeitsstufen."
  },
  {
    id: 8,
    slug: "pokemon-elite-redux",
    name: "Pokémon Elite Redux",
    type: "ROM-Hack",
    engine: "GBA",
    status: "In Entwicklung",
    language: "Englisch",
    base: "Emerald",
    version: "2.5",
    sourceKind: "Projektseite",
    sourceUrl: "https://elite-redux.com/",
    featured: 93,
    color: "#744ab0",
    symbol: "E",
    tags: ["Multi-Ability", "Schwierig", "Kein Grind"],
    description: "Strategischer Kampf-Hack mit bis zu vier Fähigkeiten pro Pokémon und konsequent reduziertem Grind."
  },
  {
    id: 9,
    slug: "pokemon-emerald-seaglass",
    name: "Pokémon Emerald Seaglass",
    type: "ROM-Hack",
    engine: "GBA",
    status: "Komplett",
    language: "Englisch",
    base: "Emerald",
    version: "3.0",
    sourceKind: "Release-Beitrag",
    sourceUrl: "https://www.reddit.com/r/PokemonROMhacks/comments/1fm9sbg/pok%C3%A9mon_emerald_seaglass_version_30_is_out_now/",
    featured: 92,
    color: "#559bad",
    symbol: "S",
    tags: ["GBC-Stil", "Hoenn", "Entspannt"],
    description: "Emerald in liebevoller GBC-Optik mit modernisiertem Pokédex und zahlreichen Komfortfunktionen."
  },
  {
    id: 10,
    slug: "pokemon-polished-crystal",
    name: "Pokémon Polished Crystal",
    type: "ROM-Hack",
    engine: "GBC",
    status: "Komplett",
    language: "Englisch",
    base: "Crystal",
    version: "3.2.3",
    sourceKind: "Entwickler-Repository",
    sourceUrl: "https://github.com/Rangi42/polishedcrystal",
    featured: 88,
    color: "#5689c8",
    symbol: "C",
    tags: ["Johto", "QoL", "Open Source"],
    description: "Eine behutsam modernisierte Crystal-Version mit Bugfixes, neuen Optionen und wiederhergestellten Inhalten."
  },
  {
    id: 11,
    slug: "pokemon-prism",
    name: "Pokémon Prism",
    type: "ROM-Hack",
    engine: "GBC",
    status: "In Entwicklung",
    language: "Englisch",
    base: "Crystal",
    version: "0.95.0254",
    sourceKind: "Projektseite",
    sourceUrl: "https://rainbowdevs.com/title/prism/",
    featured: 89,
    color: "#875aae",
    symbol: "P",
    tags: ["Neue Region", "20 Orden", "Retro"],
    description: "Ein technisch ambitioniertes Crystal-Abenteuer in Naljo mit neuen Typen, Minispielen und vielen Regionen."
  },
  {
    id: 12,
    slug: "pokemon-renegade-platinum",
    name: "Pokémon Renegade Platinum",
    type: "ROM-Hack",
    engine: "NDS",
    status: "Komplett",
    language: "Englisch",
    base: "Platinum",
    version: "1.3.0",
    sourceKind: "Community-Thread",
    sourceUrl: "https://projectpokemon.org/home/forums/topic/52294-pok%C3%A9mon-renegade-platinum/",
    featured: 95,
    color: "#9a7eb9",
    symbol: "P",
    tags: ["Sinnoh", "Schwierig", "493 Pokémon"],
    description: "Drayanos Komplettüberarbeitung von Platinum mit allen 493 Pokémon und anspruchsvolleren Bosskämpfen."
  },
  {
    id: 13,
    slug: "blaze-black-2-volt-white-2-redux",
    name: "Blaze Black 2 / Volt White 2 Redux",
    type: "ROM-Hack",
    engine: "NDS",
    status: "Komplett",
    language: "Englisch",
    base: "Black 2 / White 2",
    version: "1.4.1",
    sourceKind: "Community-Dokumentation",
    sourceUrl: "https://smilingzero.github.io/BlazeBlack2ReduxWiki/",
    featured: 87,
    color: "#66747b",
    symbol: "B",
    tags: ["Einall", "649 Pokémon", "Schwierig"],
    description: "Eine modernisierte Neuinterpretation von Drayanos Einall-Hacks mit drei Spielmodi und viel Postgame."
  },
  {
    id: 14,
    slug: "sacred-gold-storm-silver",
    name: "Sacred Gold / Storm Silver",
    type: "ROM-Hack",
    engine: "NDS",
    status: "Komplett",
    language: "Englisch",
    base: "HeartGold / SoulSilver",
    version: "1.05",
    sourceKind: "Community-Thread",
    sourceUrl: "https://gbatemp.net/threads/pokemon-sacred-gold-storm-silver.327567/",
    featured: 84,
    color: "#b68c44",
    symbol: "S",
    tags: ["Johto", "Schwierig", "493 Pokémon"],
    description: "Die klassischen Johto-Remakes als forderndes, vollständigeres Abenteuer mit erweitertem Pokédex."
  },
  {
    id: 15,
    slug: "luminescent-platinum",
    name: "Luminescent Platinum",
    type: "ROM-Hack",
    engine: "Switch",
    status: "In Entwicklung",
    language: "Englisch",
    base: "Brilliant Diamond",
    version: "2.0.2f",
    sourceKind: "Projektseite",
    sourceUrl: "https://luminescent.team/",
    featured: 81,
    color: "#6778c8",
    symbol: "L",
    tags: ["Sinnoh", "Schwierig", "Mod"],
    description: "Ein umfangreicher BDSP-Mod, stark von Renegade Platinum inspiriert und für erfahrene Spieler gedacht."
  },
  {
    id: 16,
    slug: "pokemon-modern-emerald",
    name: "Pokémon Modern Emerald",
    type: "ROM-Hack",
    engine: "GBA",
    status: "Komplett",
    language: "Englisch",
    base: "Emerald",
    version: "Aktuell",
    sourceKind: "Entwickler-Repository",
    sourceUrl: "https://github.com/resetes12/pokeemerald",
    featured: 72,
    color: "#2d9566",
    symbol: "M",
    tags: ["Hoenn", "QoL", "Anpassbar"],
    description: "Emerald mit vielen konfigurierbaren modernen Mechaniken, ohne das Grundgefühl stark zu verändern."
  },
  {
    id: 17,
    slug: "pokemon-infinite-fusion",
    name: "Pokémon Infinite Fusion",
    type: "Fan-Game",
    engine: "RPG Maker",
    status: "In Entwicklung",
    language: "Englisch",
    base: "Essentials",
    version: "Laufend",
    sourceKind: "Offizieller Community-Post",
    sourceUrl: "https://www.reddit.com/r/PokemonInfiniteFusion/comments/wydpah/game_download_and_other_important_links/",
    featured: 98,
    color: "#6a56ae",
    symbol: "∞",
    tags: ["Fusionen", "Kanto", "Kreativ"],
    description: "Kombiniere Pokémon zu tausenden handgezeichneten Fusionen und erkunde eine stark veränderte Kanto-Welt."
  },
  {
    id: 18,
    slug: "pokemon-uranium",
    name: "Pokémon Uranium",
    type: "Fan-Game",
    engine: "RPG Maker",
    status: "Komplett",
    language: "Englisch",
    base: "Essentials",
    version: "Community Edition",
    sourceKind: "Projektseite",
    sourceUrl: "https://pokemonuranium.co/",
    featured: 90,
    color: "#9b9144",
    symbol: "U",
    tags: ["Fakemon", "Nuclear-Typ", "Neue Region"],
    description: "Eine große Reise durch Tandor mit über 150 eigenen Spezies und dem exklusiven Nuclear-Typ."
  },
  {
    id: 19,
    slug: "pokemon-insurgence",
    name: "Pokémon Insurgence",
    type: "Fan-Game",
    engine: "RPG Maker",
    status: "Komplett",
    language: "Englisch",
    base: "Essentials",
    version: "Aktuell",
    sourceKind: "Projektseite",
    sourceUrl: "https://p-insurgence.com/",
    featured: 92,
    color: "#5c476e",
    symbol: "I",
    tags: ["Delta Species", "Düstere Story", "Online"],
    description: "Ein umfangreiches Abenteuer in Torren mit Delta Species, eigenen Mega-Entwicklungen und Challenge-Modi."
  },
  {
    id: 20,
    slug: "pokemon-reborn",
    name: "Pokémon Reborn",
    type: "Fan-Game",
    engine: "RPG Maker",
    status: "Komplett",
    language: "Englisch",
    base: "Essentials",
    version: "19.5",
    sourceKind: "Projektseite",
    sourceUrl: "https://www.rebornevo.com/pr/index.html/",
    featured: 96,
    color: "#70516b",
    symbol: "R",
    tags: ["18 Arenen", "Field Effects", "100+ Stunden"],
    description: "Ein langes, anspruchsvolles Abenteuer in einer verfallenen Metropole mit eigenem Terrain-System."
  },
  {
    id: 21,
    slug: "pokemon-rejuvenation",
    name: "Pokémon Rejuvenation",
    type: "Fan-Game",
    engine: "RPG Maker",
    status: "In Entwicklung",
    language: "Englisch",
    base: "Essentials",
    version: "14.0.0",
    sourceKind: "Projektseite",
    sourceUrl: "https://www.rebornevo.com/rejuvdown/",
    featured: 94,
    color: "#d26975",
    symbol: "J",
    tags: ["Story", "Gen 9", "Mehrere Routen"],
    description: "Ein riesiges, storylastiges Fan-Game mit verzweigten Routen, modernen Generationen und 18 Arenen."
  },
  {
    id: 22,
    slug: "pokemon-opalo",
    name: "Pokémon Ópalo",
    type: "Fan-Game",
    engine: "RPG Maker",
    status: "Komplett",
    language: "Mehrsprachig",
    base: "Essentials",
    version: "Komplett",
    sourceKind: "Entwicklerseite",
    sourceUrl: "https://ericlostie.vercel.app/",
    featured: 89,
    color: "#d97254",
    symbol: "O",
    tags: ["Western", "16 Arenen", "Zwei Regionen"],
    description: "Eine ambitionierte Western-Geschichte über zwei Regionen und insgesamt 16 Arenen."
  },
  {
    id: 23,
    slug: "pokemon-anil",
    name: "Pokémon Añil",
    type: "Fan-Game",
    engine: "RPG Maker",
    status: "Komplett",
    language: "Mehrsprachig",
    base: "Essentials",
    version: "Komplett",
    sourceKind: "Entwicklerseite",
    sourceUrl: "https://ericlostie.vercel.app/",
    featured: 82,
    color: "#3e78a8",
    symbol: "A",
    tags: ["Kanto", "Remake", "Gen 9"],
    description: "Ein vollständig modernisiertes Kanto-Remake mit überarbeiteter Handlung und optional erweitertem Pokédex."
  },
  {
    id: 24,
    slug: "pokemon-iberia",
    name: "Pokémon Iberia",
    type: "Fan-Game",
    engine: "RPG Maker",
    status: "Komplett",
    language: "Mehrsprachig",
    base: "Essentials",
    version: "Komplett",
    sourceKind: "Entwicklerseite",
    sourceUrl: "https://ericlostie.vercel.app/",
    featured: 75,
    color: "#d39a42",
    symbol: "I",
    tags: ["Spanien", "Humor", "Regionalformen"],
    description: "Eine humorvolle Reise durch eine von der Iberischen Halbinsel inspirierte Region."
  },
  {
    id: 25,
    slug: "pokemon-xenoverse",
    name: "Pokémon Xenoverse",
    type: "Fan-Game",
    engine: "RPG Maker",
    status: "Komplett",
    language: "Mehrsprachig",
    base: "Essentials",
    version: "Komplett",
    sourceKind: "Entwicklerkanal",
    sourceUrl: "https://www.youtube.com/@WEEDleChannel",
    featured: 91,
    color: "#2c7c91",
    symbol: "X",
    tags: ["Fakemon", "Neue Region", "Story"],
    description: "Eine eigenständige Welt mit neuen Spezies, X-Pokémon und besonders aufwendiger Präsentation."
  },
  {
    id: 26,
    slug: "pokerogue",
    name: "PokéRogue",
    type: "Fan-Game",
    engine: "Browser",
    status: "In Entwicklung",
    language: "Mehrsprachig",
    base: "Eigene Engine",
    version: "Laufend",
    sourceKind: "Offizielle Web-App",
    sourceUrl: "https://pagefaultgames.github.io/pokerogue/main/index.html",
    featured: 97,
    color: "#337c68",
    symbol: "P",
    tags: ["Browser", "Roguelite", "Runs"],
    description: "Ein direkt im Browser spielbares Roguelite mit Biomen, stapelbaren Items und Meta-Fortschritt."
  },
  {
    id: 27,
    slug: "pokemon-eon-guardians",
    name: "Pokémon Eon Guardians",
    type: "Fan-Game",
    engine: "RPG Maker",
    status: "Komplett",
    language: "Deutsch",
    base: "Essentials",
    version: "Komplett",
    sourceKind: "Community-Thread",
    sourceUrl: "https://www.pokecommunity.com/threads/pok%C3%A9mon-eon-guardians.461928/",
    featured: 80,
    color: "#c8923b",
    symbol: "E",
    tags: ["Deutsch", "Neue Region", "Story"],
    description: "Ein deutschsprachiges Fan-Abenteuer in der vielfältigen Hakken-Region mit klassischem Spielgefühl."
  },
  {
    id: 28,
    slug: "pokemon-crystal-clear",
    name: "Pokémon Crystal Clear",
    type: "ROM-Hack",
    engine: "GBC",
    status: "Komplett",
    language: "Englisch",
    base: "Crystal",
    version: "Laufend gepflegt",
    sourceKind: "Entwicklerseite",
    sourceUrl: "https://shockslayer.com/crystal-clear/",
    featured: 96,
    color: "#4b8fa8",
    symbol: "C",
    tags: ["Open World", "Johto", "Kanto"],
    description: "Crystal als offene Welt mit frei wählbarer Startregion, skalierenden Arenen und zahlreichen Charakteroptionen."
  },
  {
    id: 29,
    slug: "pokemon-coral",
    name: "Pokémon Coral",
    type: "ROM-Hack",
    engine: "GBC",
    status: "Demo",
    language: "Englisch",
    base: "Crystal",
    version: "Demo 2022",
    sourceKind: "Entwickler-Repository",
    sourceUrl: "https://github.com/pkmncoraldev/polishedcoral",
    featured: 89,
    color: "#e06f62",
    symbol: "C",
    tags: ["Neue Region", "Retro", "Fakemon"],
    description: "Ein detailreiches Gen-2-Abenteuer in der Onwa-Region mit neuen Pokémon, Fähigkeiten und flüssiger Technik."
  },
  {
    id: 30,
    slug: "pokemon-crown",
    name: "Pokémon Crown",
    type: "ROM-Hack",
    engine: "GBA",
    status: "Demo",
    language: "Englisch",
    base: "FireRed",
    version: "Demo 1.0.9",
    sourceKind: "Community-Thread",
    sourceUrl: "https://www.pokecommunity.com/threads/pok%C3%A9mon-crown.463821/",
    featured: 88,
    color: "#a27a38",
    symbol: "♛",
    tags: ["Auto-Battler", "Mittelalter", "Neue Region"],
    description: "Ein ungewöhnlicher FireRed-Hack, der Erkundung und Teamaufbau mit taktischen Auto-Battler-Kämpfen verbindet."
  },
  {
    id: 31,
    slug: "pokemon-odyssey",
    name: "Pokémon Odyssey",
    type: "ROM-Hack",
    engine: "GBA",
    status: "Komplett",
    language: "Englisch",
    base: "FireRed",
    version: "4.0",
    sourceKind: "Community-Thread",
    sourceUrl: "https://www.pokecommunity.com/threads/pok%C3%A9mon-odyssey-complete-v4-0.488536/",
    featured: 95,
    color: "#496e89",
    symbol: "O",
    tags: ["Dungeon Crawler", "Story", "Regionalformen"],
    description: "Ein von Etrian Odyssey inspirierter Dungeon-Crawler mit Labyrinth-Ebenen, FOEs und eigener Handlung."
  },
  {
    id: 32,
    slug: "pokemon-quetzal",
    name: "Pokémon Quetzal",
    type: "ROM-Hack",
    engine: "GBA",
    status: "In Entwicklung",
    language: "Mehrsprachig",
    base: "Emerald",
    version: "Laufend",
    sourceKind: "Projektseite",
    sourceUrl: "https://www.pokemonquetzal.app/",
    featured: 91,
    color: "#2f9a74",
    symbol: "Q",
    tags: ["Koop", "Hoenn", "Open World"],
    description: "Eine stark erweiterte Emerald-Variante mit Koop-Mehrspieler, sichtbaren Begegnungen und vielen Spieloptionen."
  },
  {
    id: 33,
    slug: "pokemon-emerald-legacy",
    name: "Pokémon Emerald Legacy",
    type: "ROM-Hack",
    engine: "GBA",
    status: "Komplett",
    language: "Englisch",
    base: "Emerald",
    version: "1.1.4",
    sourceKind: "Entwickler-Repository",
    sourceUrl: "https://github.com/cRz-Shadows/Pokemon_Emerald_Legacy",
    featured: 85,
    color: "#37875e",
    symbol: "E",
    tags: ["Hoenn", "Klassisch", "QoL"],
    description: "Eine nostalgietreue Überarbeitung von Emerald mit besserer Balance, überarbeiteter Handlung und Postgame."
  },
  {
    id: 34,
    slug: "pokemon-crystal-legacy",
    name: "Pokémon Crystal Legacy",
    type: "ROM-Hack",
    engine: "GBC",
    status: "Komplett",
    language: "Englisch",
    base: "Crystal",
    version: "1.3.1",
    sourceKind: "Entwickler-Repository",
    sourceUrl: "https://github.com/cRz-Shadows/Pokemon_Crystal_Legacy",
    featured: 84,
    color: "#467daf",
    symbol: "C",
    tags: ["Johto", "Klassisch", "Balance"],
    description: "Crystal mit behutsam verbesserter Johto-Reise, neu ausbalancierten Pokémon und sinnvollerem Levelverlauf."
  },
  {
    id: 35,
    slug: "pokemon-yellow-legacy",
    name: "Pokémon Yellow Legacy",
    type: "ROM-Hack",
    engine: "GBC",
    status: "Komplett",
    language: "Englisch",
    base: "Yellow",
    version: "1.0.10",
    sourceKind: "Entwickler-Repository",
    sourceUrl: "https://github.com/cRz-Shadows/Pokemon_Yellow_Legacy",
    featured: 82,
    color: "#c49a32",
    symbol: "Y",
    tags: ["Kanto", "Klassisch", "Balance"],
    description: "Eine originalgetreue Modernisierung von Yellow mit besserer Pokémon-Verteilung und überarbeiteten Kämpfen."
  },
  {
    id: 36,
    slug: "pokemon-black-and-white-3-genesis",
    name: "Pokémon Black and White 3: Genesis",
    type: "ROM-Hack",
    engine: "GBC",
    status: "Komplett",
    language: "Englisch",
    base: "Crystal",
    version: "1.2.0",
    sourceKind: "Entwickler-Repository",
    sourceUrl: "https://github.com/AzureKeys/BW3G",
    featured: 87,
    color: "#4d5961",
    symbol: "3",
    tags: ["Einall", "Neue Story", "Retro"],
    description: "Eine eigenständige Einall-Fortsetzung im Gen-2-Stil, die Jahre nach Black 2 und White 2 spielt."
  },
  {
    id: 37,
    slug: "pokemon-fools-gold",
    name: "Pokémon Fool's Gold",
    type: "ROM-Hack",
    engine: "GBC",
    status: "Komplett",
    language: "Englisch",
    base: "Crystal",
    version: "1.3.1",
    sourceKind: "Originaler Entwicklerbeitrag",
    sourceUrl: "https://www.reddit.com/r/PokemonROMhacks/comments/g1ars3/a_couple_of_my_friends_and_i_put_together_a_rom/",
    featured: 86,
    color: "#c08a3c",
    symbol: "F",
    tags: ["Regionalformen", "Johto", "Kreativ"],
    description: "Jede bekannte Gen-1- und Gen-2-Spezies erhält neue Typen, Designs und Fundorte in einem veränderten Johto."
  },
  {
    id: 38,
    slug: "pokemon-tectonic",
    name: "Pokémon Tectonic",
    type: "Fan-Game",
    engine: "RPG Maker",
    status: "Komplett",
    language: "Englisch",
    base: "Essentials",
    version: "3.x",
    sourceKind: "Projektseite",
    sourceUrl: "https://www.tectonic-game.com/",
    featured: 94,
    color: "#915746",
    symbol: "T",
    tags: ["Neue Region", "Teambuilding", "QoL"],
    description: "Ein umfangreiches Abenteuer in Makya mit neu gedachter Balance, eigener Kampf-KI und wenig Grind."
  },
  {
    id: 39,
    slug: "pokemon-desolation",
    name: "Pokémon Desolation",
    type: "Fan-Game",
    engine: "RPG Maker",
    status: "In Entwicklung",
    language: "Englisch",
    base: "Essentials",
    version: "Episode 6",
    sourceKind: "Projektseite",
    sourceUrl: "https://www.rebornevo.com/deso/index.php/",
    featured: 88,
    color: "#744d4f",
    symbol: "D",
    tags: ["Düstere Story", "Field Effects", "Entscheidungen"],
    description: "Ein charaktergetriebenes Abenteuer mit verzweigter Handlung, schwierigen Kämpfen und eigenen Feld-Effekten."
  },
  {
    id: 40,
    slug: "pokemon-flux",
    name: "Pokémon Flux",
    type: "Fan-Game",
    engine: "RPG Maker",
    status: "In Entwicklung",
    language: "Englisch",
    base: "Essentials",
    version: "2.1.0",
    sourceKind: "Projekt-Showcase",
    sourceUrl: "https://eeveeexpo.com/flux/",
    featured: 92,
    color: "#4369a8",
    symbol: "F",
    tags: ["Fakemon", "Neue Region", "Online"],
    description: "Eine neue Region mit Alter-Pokémon, Flux-Attacken, sichtbaren Begegnungen und experimentellen Online-Funktionen."
  },
  {
    id: 41,
    slug: "pokemon-showdown",
    name: "Pokémon Showdown",
    type: "Fan-Game",
    engine: "Browser",
    status: "In Entwicklung",
    language: "Mehrsprachig",
    base: "Eigene Engine",
    version: "Laufend",
    sourceKind: "Offizielle Web-App",
    sourceUrl: "https://pokemonshowdown.com/",
    featured: 93,
    color: "#5676a8",
    symbol: "S",
    tags: ["Online", "Kampfsimulator", "Teambuilding"],
    description: "Der etablierte Browser-Kampfsimulator mit sofortigem Teambau, vielen Formaten und weltweitem Matchmaking."
  },
  {
    id: 42,
    slug: "pokemon-blaze-online",
    name: "Pokémon Blaze Online",
    type: "Fan-Game",
    engine: "Browser",
    status: "In Entwicklung",
    language: "Englisch",
    base: "Eigene Engine",
    version: "Public Alpha",
    sourceKind: "Projektseite",
    sourceUrl: "https://www.pokemonblazeonline.com/",
    featured: 79,
    color: "#cf613d",
    symbol: "B",
    tags: ["MMO", "Online", "Koop"],
    description: "Ein plattformübergreifendes Fan-MMO mit gemeinsamer Welt, Handel, Crews und kooperativen Kämpfen."
  },
  {
    id: 43,
    slug: "pokemon-z",
    name: "Pokémon Z",
    type: "Fan-Game",
    engine: "RPG Maker",
    status: "Komplett",
    language: "Mehrsprachig",
    base: "Essentials",
    version: "Komplett",
    sourceKind: "Entwicklerseite",
    sourceUrl: "https://ericlostie.vercel.app/",
    featured: 90,
    color: "#a84f63",
    symbol: "Z",
    tags: ["Kalos", "Neue Story", "Gen 9"],
    description: "Eric Losties Neuinterpretation einer fehlenden Kalos-Edition mit eigener Geschichte und modernen Pokémon."
  },
  {
    id: 44,
    slug: "pokeforce",
    name: "PokéForce",
    type: "Fan-Game",
    engine: "Browser",
    status: "In Entwicklung",
    language: "Englisch",
    base: "Eigene Engine",
    version: "Alpha",
    sourceKind: "Projektseite",
    sourceUrl: "https://pokeforce.org/",
    featured: 74,
    color: "#4d8b72",
    symbol: "P",
    tags: ["MMO", "Johto", "Online"],
    description: "Ein browserbasiertes Fan-MMO in einer neu interpretierten Johto-Region mit gemeinsamer Spielwelt."
  }
];

/* Nur redaktionell freigegebene Ergänzungen; discovery/inbox.json wird nie geladen. */
for (const reviewed of window.PATCHDEX_REVIEWED_GAMES || []) {
  const index = window.PATCHDEX_GAMES.findIndex(game => game.slug === reviewed.slug);
  if (index < 0) window.PATCHDEX_GAMES.push(reviewed);
  else window.PATCHDEX_GAMES[index] = { ...window.PATCHDEX_GAMES[index], ...reviewed };
}

/* Das Datum bleibt am Datensatz und kann bei Einzelprüfungen überschrieben werden. */
for (const game of window.PATCHDEX_GAMES) {
  game.reviewedAt ||= "2026-09-12";
  game.aliases ||= [];
  game.developer ||= "";
  game.region ||= game.tags.find(tag => ["Kanto", "Johto", "Hoenn", "Sinnoh", "Einall", "Kalos", "Neue Region"].includes(tag)) || "";
}
